
package it.conispesemediche.stubInvioFile;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "InvioTelematicoSpeseSanitarie730pService", targetNamespace = "http://ejb.invioTelematicoSS730p.sanita.finanze.it/", wsdlLocation = "file:/C:/Users/Vincenzo/git/GestioneSoci/src/main/java/it/conispesemediche/stubfromwsdl/InvioTelematicoSpeseSanitarie730p.wsdl")
public class InvioTelematicoSpeseSanitarie730PService
    extends Service
{

    private final static URL INVIOTELEMATICOSPESESANITARIE730PSERVICE_WSDL_LOCATION;
    private final static WebServiceException INVIOTELEMATICOSPESESANITARIE730PSERVICE_EXCEPTION;
    private final static QName INVIOTELEMATICOSPESESANITARIE730PSERVICE_QNAME = new QName("http://ejb.invioTelematicoSS730p.sanita.finanze.it/", "InvioTelematicoSpeseSanitarie730pService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Vincenzo/git/GestioneSoci/src/main/java/it/conispesemediche/stubfromwsdl/InvioTelematicoSpeseSanitarie730p.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INVIOTELEMATICOSPESESANITARIE730PSERVICE_WSDL_LOCATION = url;
        INVIOTELEMATICOSPESESANITARIE730PSERVICE_EXCEPTION = e;
    }

    public InvioTelematicoSpeseSanitarie730PService() {
        super(__getWsdlLocation(), INVIOTELEMATICOSPESESANITARIE730PSERVICE_QNAME);
    }

    public InvioTelematicoSpeseSanitarie730PService(WebServiceFeature... features) {
        super(__getWsdlLocation(), INVIOTELEMATICOSPESESANITARIE730PSERVICE_QNAME, features);
    }

    public InvioTelematicoSpeseSanitarie730PService(URL wsdlLocation) {
        super(wsdlLocation, INVIOTELEMATICOSPESESANITARIE730PSERVICE_QNAME);
    }

    public InvioTelematicoSpeseSanitarie730PService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INVIOTELEMATICOSPESESANITARIE730PSERVICE_QNAME, features);
    }

    public InvioTelematicoSpeseSanitarie730PService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InvioTelematicoSpeseSanitarie730PService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InvioTelematicoSS730PMtom
     */
    @WebEndpoint(name = "InvioTelematicoSS730pMtomPort")
    public InvioTelematicoSS730PMtom getInvioTelematicoSS730PMtomPort() {
        return super.getPort(new QName("http://ejb.invioTelematicoSS730p.sanita.finanze.it/", "InvioTelematicoSS730pMtomPort"), InvioTelematicoSS730PMtom.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InvioTelematicoSS730PMtom
     */
    @WebEndpoint(name = "InvioTelematicoSS730pMtomPort")
    public InvioTelematicoSS730PMtom getInvioTelematicoSS730PMtomPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ejb.invioTelematicoSS730p.sanita.finanze.it/", "InvioTelematicoSS730pMtomPort"), InvioTelematicoSS730PMtom.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INVIOTELEMATICOSPESESANITARIE730PSERVICE_EXCEPTION!= null) {
            throw INVIOTELEMATICOSPESESANITARIE730PSERVICE_EXCEPTION;
        }
        return INVIOTELEMATICOSPESESANITARIE730PSERVICE_WSDL_LOCATION;
    }

}
